[colors]
[colors.primary]
background = '#16181a'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#16181a'
red = '#ff6e5e'
green = '#5eff6c'
yellow = '#f1ff5e'
blue = '#5ea1ff'
magenta = '#ff5ef1'
cyan = '#5ef1ff'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#7b8496'
red = '#ff6e5e'
green = '#5eff6c'
yellow = '#f1ff5e'
blue = '#5ea1ff'
magenta = '#ff5ef1'
cyan = '#5ef1ff'
white = '#ffffff'

[colors.selection]
text = '#f1ff5e'
background = '#3c4048'
