[colors]
[colors.primary]
background = '#00060e'
foreground = '#fee801'

# Normal colors
[colors.normal]
black = '#00060e'
red = '#9a9f17'
green = '#39c4b6'
yellow = '#fee801'
blue = '#39c4b6'
magenta = '#9a9f17'
cyan = '#39c4b6'
white = '#fee801'

# Bright colors
[colors.bright]
black = '#9a9f17'
red = '#9a9f17'
green = '#39c4b6'
yellow = '#fee801'
blue = '#39c4b6'
magenta = '#9a9f17'
cyan = '#39c4b6'
white = '#fee801'

[colors.selection]
background = '#9a9f17'
