[colors]
[colors.primary]
background = '#0d131a'
foreground = '#e2e8f0'

# Normal colors
[colors.normal]
black = '#161e26'
red = '#ff4545'
green = '#25d0ab'
yellow = '#ffcc00'
blue = '#3399ff'
magenta = '#d580ff'
cyan = '#00e5ff'
white = '#e2e8f0'

# Bright colors
[colors.bright]
black = '#505c68'
red = '#ff884d'
green = '#00ffea'
yellow = '#ffe066'
blue = '#6ecfff'
magenta = '#f09eff'
cyan = '#79fffc'
white = '#ffffff'

[colors.selection]
background = '#1c4e80'
foreground = '#e2e8f0'
