[colors]
[colors.primary]
background = '#012e21'
foreground = '#e2e8f0'

# Normal colors
[colors.normal]
black = '#4a5568'
red = '#f56565'
green = '#04c755'
yellow = '#ff9d26'
blue = '#63ed91'
magenta = '#4fd19d'
cyan = '#4fd181'
white = '#f7fafc'

# Bright colors
[colors.bright]
black = '#6a7588'
red = '#ff8585'
green = '#68db98'
yellow = '#d68700'
blue = '#83ffcd'
magenta = '#6fe5ac'
cyan = '#6fe5ae'
white = '#f7fafc'

[colors.selection]
text = '#e2e8f0'
background = '#505c68'
