[colors]
[colors.primary]
background = '#1A202C'
foreground = '#E2E8F0'

# Normal colors
[colors.normal]
black = '#4A5568'
red = '#F56565'
green = '#48BB78'
yellow = '#F6AD55'
blue = '#63edcd'
magenta = '#4FD1C5'
cyan = '#4FD1C5'
white = '#F7FAFC'

# Bright colors
[colors.bright]
black = '#6A7588'
red = '#FF8585'
green = '#68DB98'
yellow = '#FFCD75'
blue = '#83fff5'
magenta = '#6FE1E5'
cyan = '#6FE1E5'
white = '#F7FAFC'

[colors.selection]
text = '#E2E8F0'
background = '#505C68'
