[colors]
[colors.primary]
background = '#05080d'
foreground = '#cdd6f4'

# Normal colors
[colors.normal]
black = '#1e293b'
red = '#ff4444'
green = '#00ffcc'
yellow = '#ffcc00'
blue = '#00aaff'
magenta = '#d670d6'
cyan = '#00e5ff'
white = '#cdd6f4'

# Bright colors
[colors.bright]
black = '#3b4252'
red = '#ff6666'
green = '#33ffdd'
yellow = '#ffd633'
blue = '#33bbff'
magenta = '#e085e0'
cyan = '#33ecff'
white = '#ffffff'

[colors.selection]
text = '#05080d'
background = '#1e293b'
